language: python
sudo: required
dist: trusty

python:
    - 3.4

branches:
  only:
    - master
    - travis # To debug .travis.yml

addons:
  apt:
    packages:
      - libhdf5-serial-dev

install:
  - pip install -r requirements.txt

script:
  # Stop on first error
  - set -e

  # Build, test irbasis

Untracked files:
  (use "git add <file>..." to include in what will be committed)
  - cd $TRAVIS_BUILD_DIR/..
  - mkdir build
  - cd build
  - |
    cmake ../irbasis  \
    -DCMAKE_BUILD_TYPE=Debug                              \
    -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/installed
  - make test
