language: python
sudo: required
dist: trusty

python:
    - 2.6
    - 2.7
    - 3.4
    - 3.5
    - 3.6

branches:
  only:
    - master
    - travis # To debug .travis.yml

addons:
  apt:
    packages:
      - libhdf5-serial-dev

install:
  - pip install -r python/requirements.txt

script:
  # Stop on first error
  - set -e

  # Build, test irbasis
  - cd $TRAVIS_BUILD_DIR/..
  - mkdir build
  - cd build
  - |
    cmake ../irbasis  \
    -DCMAKE_BUILD_TYPE=Debug                              \
    -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/installed
  - make
  - make test
  - python setup.py bdist_wheel
  - cd dist
  - pip install irbasis-*.whl
